import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import React from "react";
import ThemeSwitcher from './components/ThemeSwitcher';
import ClientNavBar from './components/ClientNavBar';
import Footer from './components/Footer';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

const Layout = ({ children }) => {
  return (
    <ClerkProvider>
      <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
        <body className="antialiased">
          <header>
            <ClientNavBar />
            <ThemeSwitcher />
            <SignedOut>
              <div className="auth-buttons">
                <SignInButton />
                <SignUpButton />
              </div>
            </SignedOut>
            <SignedIn>
              <div className="user-button">
                <UserButton />
              </div>
            </SignedIn>
          </header>
          <main>{children}</main>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
};

export default Layout;